extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- attoparsec
- bytestring

executables:
  processor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Weverything
    - -Wno-safe
    - -Wno-prepositive-qualified-module
    - -Wno-implicit-prelude
    - -Wno-missing-safe-haskell-mode
    - -Wno-missing-import-lists
